env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
ignorePatterns:
  - src/old/**/*
  - src/linted/**/*
  - rollup.config.js
rules:
  indent:
    - warn
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
    - avoidEscape: true
  semi:
    - error
    - never
  eqeqeq:
    - error
    - smart
  "@typescript-eslint/no-empty-interface": off
  "@typescript-eslint/no-empty-function": off
