export const ObstacleStructures = [
  STRUCTURE_EXTENSION,
  STRUCTURE_SPAWN,
  STRUCTURE_LINK,
  STRUCTURE_WALL,
  STRUCTURE_KEEPER_LAIR,
  STRUCTURE_CONTROLLER,
  STRUCTURE_STORAGE,
  STRUCTURE_TOWER,
  STRUCTURE_OBSERVER,
  STRUCTURE_POWER_BANK,
  STRUCTURE_POWER_SPAWN,
  STRUCTURE_EXTRACTOR,
  STRUCTURE_LAB,
  STRUCTURE_TERMINAL,
  STRUCTURE_NUKER,
  STRUCTURE_FACTORY,
  STRUCTURE_INVADER_CORE,

  // 通常はObstacleとして扱う
  STRUCTURE_RAMPART,
  STRUCTURE_PORTAL,
]

export const WalkableStructures = [
  STRUCTURE_ROAD,
  STRUCTURE_CONTAINER,
] as const
