name: Run Test

on:
  pull_request:
    types: [ opened, reopened, edited, synchronize ]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn jest

